### ISSUE TITLE
Improve the Frontend

### ISSUE THREAD

**Issue by megabyte0x** [megabyte0x/The-Quest-NFTs#1]
Improve the Frontend of the whole website in anyway you see fit.

**Comment by Navansh** [comment]
On it

**Comment by megabyte0x** [comment]
You can take inspiration from here 

https://opensea.io/collection/the-quest-polygon-advocates


https://polygon.technology/brandguidelines

**Comment by varun-doshi** [comment]
> Improve the Frontend of the whole website in anyway you see fit.

Getting this done asap

**Comment by megabyte0x** [comment]
> > Improve the Frontend of the whole website in anyway you see fit.
> 
> 
> 
> Getting this done asap

Thanks for showing the interest. @Navansh have already made a pull request for it [here](https://github.com/megabyte0x/The-Quest-NFTs/pull/2). I would suggest you to check it out and improve it further. 

Ill merge it on dev branch and you can take it further. 

A suggestion: make anime theme oriented.

**Comment by megabyte0x** [comment]
Check this #3 out @Navansh @varun-doshi
