### ISSUE TITLE
Change the theme to Anime Related

### ISSUE THREAD

**Issue by megabyte0x** [megabyte0x/The-Quest-NFTs#3]
All [THE QUEST NFTs](https://opensea.io/collection/the-quest-polygon-advocates) are anime related, therefore it will make a lot of sense to have the same theme.

- [ ] Created the PR in the `dev` branch.
- [ ] PR contains the screen recording of the changes.

**Comment by 0xPrakharG** [comment]
Please Assign this issue to me.

**Comment by megabyte0x** [comment]
You got it 🫡

**Comment by megabyte0x** [comment]
@0xPrakharG 

https://advocate-quest-git-dev-megabyte0x.vercel.app/

This is having an issue with the background image. It's not a free image which is causing the watermark to appear in it background.

**Comment by megabyte0x** [comment]
Thanks

**Comment by 0xPrakharG** [comment]
💜🫡
