### ISSUE TITLE
Create Table to showcase the Latest Transactions

### ISSUE THREAD

**Issue by megabyte0x** [megabyte0x/The-Quest-NFTs#4]
I have set up the API in this [commit](https://github.com/megabyte0x/The-Quest-NFTs/commit/55fd9f5ef23d52677e0e501460c800272009cd39).

### Your Task

- [ ] Create a table with proper visibility and font \
- [ ] Show the data fetched from the API
- [ ] Manage the React state correctly to avoid breakdowns.

**Comment by 0xgun** [comment]
Please Assign this issue to me.

**Comment by megabyte0x** [comment]
Sure ser 🫡
